package com.wildbeeslabs.jentle.algorithms.utils;

import lombok.experimental.UtilityClass;

import java.util.*;
import java.util.function.Function;

import static java.util.Arrays.stream;
import static java.util.stream.Collectors.joining;

@UtilityClass
public class ClassUtils {

    public static List<Class<?>> getAllSuperclasses(final Class<?> cls) {
        if (Objects.isNull(cls)) {
            return null;
        }
        final List<Class<?>> classes = new ArrayList<Class<?>>();
        Class<?> superclass = cls.getSuperclass();
        while (Objects.nonNull(superclass)) {
            classes.add(superclass);
            superclass = superclass.getSuperclass();
        }
        return classes;
    }

    /**
     * <p>
     * Gets a {@code List} of all interfaces implemented by the given class and its superclasses.
     * </p>
     *
     * <p>
     * The order is determined by looking through each interface in turn as declared in the source file and following its
     * hierarchy up. Then each superclass is considered in the same way. Later duplicates are ignored, so the order is
     * maintained.
     * </p>
     *
     * @param cls the class to look up, may be {@code null}
     * @return the {@code List} of interfaces in order, {@code null} if null input
     */
    public static List<Class<?>> getAllInterfaces(final Class<?> cls) {
        if (cls == null) return null;
        final LinkedHashSet<Class<?>> interfacesFound = new LinkedHashSet<>();
        getAllInterfaces(cls, interfacesFound);
        return new ArrayList<>(interfacesFound);
    }

    /**
     * Get the interfaces for the specified class.
     *
     * @param cls             the class to look up, may be {@code null}
     * @param interfacesFound the {@code Set} of interfaces for the class
     */
    private static void getAllInterfaces(Class<?> cls, final HashSet<Class<?>> interfacesFound) {
        while (Objects.nonNull(cls)) {
            Class<?>[] interfaces = cls.getInterfaces();
            for (final Class<?> i : interfaces) {
                if (interfacesFound.add(i)) {
                    getAllInterfaces(i, interfacesFound);
                }
            }
            cls = cls.getSuperclass();
        }
    }

    /**
     * Get the fully qualified name of the supplied class.
     *
     * <p>This is a null-safe variant of {@link Class#getName()}.
     *
     * @param clazz the class whose name should be retrieved, potentially
     *              {@code null}
     * @return the fully qualified class name or {@code "null"} if the supplied
     * class reference is {@code null}
     * @see #nullSafeToString(Class...)
     * @see StringUtils#nullSafeToString(Object)
     * @since 1.3
     */
    public static String nullSafeToString(final Class<?> clazz) {
        return Objects.isNull(clazz) ? "null" : clazz.getName();
    }

    /**
     * Generate a comma-separated list of fully qualified class names for the
     * supplied classes.
     *
     * @param classes the classes whose names should be included in the
     *                generated string
     * @return a comma-separated list of fully qualified class names, or an empty
     * string if the supplied class array is {@code null} or empty
     * @see #nullSafeToString(Function, Class...)
     * @see StringUtils#nullSafeToString(Object)
     */
    public static String nullSafeToString(final Class<?>... classes) {
        return nullSafeToString(Class::getName, classes);
    }

    /**
     * Generate a comma-separated list of mapped values for the supplied classes.
     *
     * <p>The values are generated by the supplied {@code mapper}
     * (e.g., {@code Class::getName}, {@code Class::getSimpleName}, etc.), unless
     * a class reference is {@code null} in which case it will be mapped to
     * {@code "null"}.
     *
     * @param mapper  the mapper to use
     * @param classes the classes to map
     * @return a comma-separated list of mapped values, or an empty string if
     * the supplied class array is {@code null} or empty
     * @see #nullSafeToString(Class...)
     * @see StringUtils#nullSafeToString(Object)
     */
    public static String nullSafeToString(final Function<? super Class<?>, ? extends String> mapper, final Class<?>... classes) {
        if (classes == null || classes.length == 0) {
            return "";
        }
        return stream(classes).map(clazz -> Objects.isNull(clazz) ? "null" : mapper.apply(clazz)).collect(joining(", "));
    }
}
